package crawler;

import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import org.json.simple.JSONObject;
import java.io.FileWriter;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author HP
 */
public class GuiThuThap extends javax.swing.JFrame {
    //aggregate back-end class
    Crawler crawler = new Crawler();
    /**
     * Creates new form NewJFrame
     */
    public GuiThuThap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textField = new javax.swing.JTextField();
        tenBaiViet = new javax.swing.JLabel();
        addInfoButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        resultOfCrawler = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        tenBaiViet.setText("Link bài viết");

        addInfoButton.setText("Lấy thông tin");
        addInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInfoButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Xóa hết");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resultOfCrawler.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tenBaiViet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(resultOfCrawler, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(addInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenBaiViet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInfoButton)
                    .addComponent(deleteAllButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(resultOfCrawler, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void addInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInfoButtonActionPerformed
        // TODO add your handling code here:
        
        Crawler cr = new Crawler();
        cr.setUrl(textField.getText());
        //Nếu chưa nhập vào đã enter hoặc xâu ký tự không phải là url hợp lệ
        if (cr.url.isEmpty() || !cr.isValidUrl()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập URL hợp lệ!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            textField.setText("");
        } else {
            //Nếu url đã được thêm vào trước đó
            if (cr.isUrlInJson()) {
                JOptionPane.showMessageDialog(this, "URL này đã tồn tại!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                textField.setText("");
            } else {
                crawler.setUrl(cr.url);
                crawler.getDataFromUrl();
                textField.setText("");
                jEditorPane1.setContentType("text/html");
        jEditorPane1.setText(
            "<html>" +
            "<body>" +
            "<b>Link bài viết:</b> " + crawler.website + "<br>" +
            "<b>Nguồn website:</b> " + crawler.url + "<br>" +
            "<b>Loại bài viết:</b> " + crawler.blogPost + "<br>" +
            "<b>Tóm tắt bài viết (nếu có):</b> " + crawler.summary + "<br>" +
            "<b>Tiêu đề bài viết:</b> " + crawler.heading + "<br>" +
            "<b>Nội dung chi tiết bài viết:</b> " + crawler.detailedContent + "<br>" +
            "<b>Ngày tạo:</b> " + crawler.extractDate(crawler.date) + "<br>" +
            "<b>Hashtag đi kèm:</b> " + Arrays.toString(crawler.hashtags) + "<br>" +
            "<b>Tên tác giả nếu có:</b> " + crawler.extractAuthor(crawler.author) + "<br>" +
            "<b>Chuyên mục mà bài viết thuộc về:</b> " + crawler.category +
            "</body>" +
            "</html>" );
            
        jEditorPane1.setCaretPosition(0);
            }
        }
    }
    
    private void doNothing() {
    }//GEN-LAST:event_addInfoButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        // TODO add your handling code here:
        jEditorPane1.setText("");
        // Xóa dữ liệu trong file JSON
        JSONArray emptyJsonArray = new JSONArray();

        try (FileWriter fileWriter = new FileWriter("src/main/java/FileStorge/Contents.json")) {
            fileWriter.write(emptyJsonArray.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        };
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        // Xóa dữ liệu trong text area
      jEditorPane1.setText("");

    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiThuThap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiThuThap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiThuThap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiThuThap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiThuThap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInfoButton;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane resultOfCrawler;
    private javax.swing.JLabel tenBaiViet;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
